name: test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
            - name: Install
              run: npm install --no-package-lock --force
            - name: Test
              run: npm test

    publish:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: node
          uses: actions/setup-node@v2
          with:
            node-version: 18
            registry-url: https://registry.npmjs.org
        - name: publish
          run: npm publish --access public
          working-directory: my-package
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}